language: node_js
node_js:
  - "8"
  - "6"
script:
  - npm run lint
  - npm test
  # Deployment may fail due to the environment so we need to retry
  - travis_retry ./scripts/integration-tests.sh
services:
  - docker
env:
  global:
    - KUBELESS_VERSION=0.1.0
install:
  - npm install -g serverless
  - npm install