language: node_js
node_js:
  - "8"
  - "6"
script:
  - npm run lint
  - npm test
  # Deployment may fail due to the environment so we need to retry
  - travis_retry ./scripts/integration-tests.sh
services:
  - docker
env:
  global:
    - KUBELESS_VERSION: 0.3.2
    - REPO_DOMAIN: serverless
    - REPO_NAME: serverless-kubeless
    - secure: "s+L8ndj0uMNwqbLvbHePHeMJw2LI8DdEdcq1vJ98hNwHOWQc2mHVB4utG9EZFkaL+RAZYduldSJqr443d2BugxrkmzhLUlM5vDks+zHeKecwTah2uuaMUXVT/y/cWDDTVp3phqSqWbHBMG6u0ImvTVWHpnkux55S3QJTHevvhdodpO6VDTsJCEB3e1d2hHxi0L9tJrFXzQRpooV8IUuODwKBJyhK4CD7rvu0D1gBgHaUNnNLrCy4YTaFl19q5NdZUtrQDC7rpSPOhFI9CBFX8GiFq6nY3XzFASwq/JtKc3K7OLIC7Wqb6JpuvFhG6S1yhBzp73pnoE9U0Bi+YMa3L+nPoh58dCB2ldNCCCMbx7R6PWq/TwYzLvgZZ7queC2kbvCTrtU6JJfmb0CxmX1fnUIpCsNeyXaPuo4Ly6WJeAID32z79CwMo9NH0uOVTLy3LTrLcEfELhBRL5+WkMvKmXUt8yN/jEIa/H38pQN5Y/AnJ0KznO8RZ2nLhi1cR+xUkxfPVZ22Wr2XkbzJDZih/mZR+5GQBfUHWgpUChK+e8dOhplk+4PZJEO6Myja7ykXBPYtL9CV/Xi+1nQqLmfhyChiES201KusJr1IrFklslzCzgrSH8Dv2yaYUTe/Ub/I3gWIhKOXY66gkpmB6MSBJUfMK3uR4/wYfCvbtBTugsY="
install:
  - npm install -g serverless
  - npm install
after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == master && \
          "$TRAVIS_PULL_REQUEST" == false && \
          -n "$ACCESS_TOKEN" ]]; then
         ./scripts/release.sh
    fi
deploy:
  provider: npm
  email: kubernetes@bitnami.com
  api_key:
    secure: "jn9tA4DES1n4uxhD+rb7pbzux523AULAgv1f5umqAzvw9bCz7mD6nLS7fo1W8RZSPND7aPM+X5hPknyHm1L+tZbOInKNtCwFkKW2IELJ6a2OCQ+zXN/S/Cxu4dsfeDjE0kiAu5a3YejE5xEjkb98j4eC8i2N4gmdPvDLNqyMXH+W8jF/T2ivkxUGxYOMzyffmsfKmHQ2H31VZEDckcQIENUfLJuxeiBPyrppBKEOgQjpAXiAALnBUrLt741xxL7iQRDHUj8v1cmiymrERhcVpWmYvU4BonlcvPnuWK2dLglQAO+t1UoY5nXS23Lc24yXA8XMp/Bv/dHEB4WwQBNZ4vq+ImGqjFI7/HJlYpHa8eVe6rZJxNnmvBAa3HbTwTz0hoaGwAmHMqPtwelYwL92hEUV/lXQoial9WXSwIqrt24J4Q8UH7jZK3uY3LnCZggDTShSyTvzVp5Xjw/vN0xo5CDlXJ8FZpFkVUWOp7ISYEynzOlW8OZynRiboXyAgLfFMDglhDkcLCpkQLKfKSa0vZWmhgHgNsxs44cFb7pElciQ2uYQjFldXjU/4qVN65s58t4Sn69nFpSthSQKa5iwYMXbI792onVBO334pBdUFBagzP3e4Th4y2k1pFZTZ5UV5gs/2/ROK1KsM5XCi7px4Ddw1kMY4Q6PHZBaTLblqU4="
  on:
    tags: true
    repo: serverless/serverless-kubeless
