language: node_js
node_js:
  - "8"
  - "6"
script:
  - npm run lint
  - npm test
  - npm run examples
services:
  - docker
env:
  global:
    - KUBELESS_VERSION=0.0.20
install:
  # Install kubectl and a kubeadm cluster
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - ./scripts/install-minikube.sh
  - sleep 10
  # Install kubeless
  - kubectl create ns kubeless
  - curl -sL https://github.com/kubeless/kubeless/releases/download/$KUBELESS_VERSION/kubeless-$KUBELESS_VERSION.yaml | kubectl create -f -
  - curl -sL https://raw.githubusercontent.com/kubeless/kubeless/0.0.20/manifests/ingress/ingress-controller.yaml | kubectl create -f -
  - curl -LO https://github.com/kubeless/kubeless/releases/download/$KUBELESS_VERSION/kubeless_linux-amd64.zip
  - unzip kubeless_linux-amd64.zip
  - sudo mv ./bundles/kubeless_linux-amd64/kubeless /usr/local/bin/kubeless
  - sleep 20
  - kubectl get all
  # Install npm dependencies
  - npm install -g serverless
  - npm install
