service: hello-http

provider:
  name: kubeless
  runtime: python2.7

plugins:
  - serverless-kubeless

functions:
  hello-http:
    handler: handler.hello
    events:
      - http:
          path: /hello
